apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdsipeae
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdsipeae
  template:
    metadata:
      labels:
        app: hdsipeae
    spec:
      containers:
      - image: okteto.dev/hdsipeae:latest
        name: hdsipeae
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "562a9617-e3f4-41ab-a498-9cd5f8acdd97"
        - name: Vless_Path
          value: "/vlhhse46t6"
        - name: Vmess_UUID
          value: "562a9617-e3f4-41ab-a498-9cd5f8acdd97"
        - name: Vmess_Path
          value: "/vmgdtwti6"
        - name: Share_Path
          value: "/v2link"
